#!/bin/sh

set -ex
# check node from conda-forge
which node
node --version | grep v12

# check node system package and its version
/usr/bin/node --version
/usr/bin/node --version | grep v10

which npm
npm --version
npm --version | grep 6.
